"""Scenarios: a road network plus a description of the traffic that uses it.

A scenario lives in a folder with a ``scenario.yaml``, the OpenStreetMap extract and
the SUMO network built from it. Traffic is generated per episode from the demand
description, so every seed gives a different but statistically similar day.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import quoteattr

import numpy as np
import yaml

from junctioniq.sim.sumo import sumo_binary

SCENARIOS_DIR = Path(__file__).parent / "scenarios"

# SUMO vehicle types for the mix in scenario.yaml.
VEHICLE_TYPES = {
    "car": '<vType id="car" vClass="passenger" length="4.3" maxSpeed="13.9" sigma="0.5"/>',
    "motorcycle": (
        '<vType id="motorcycle" vClass="motorcycle" length="2.0" minGap="1.5" '
        'maxSpeed="13.9" accel="3.0" sigma="0.6"/>'
    ),
    "truck": '<vType id="truck" vClass="truck" length="9.0" maxSpeed="11.1" accel="1.2"/>',
}


@dataclass(frozen=True)
class DemandPeriod:
    seconds: int
    rates: dict[str, float]  # vehicles per hour, by entry name


@dataclass(frozen=True)
class Scenario:
    name: str
    folder: Path
    osm: Path
    net: Path
    netconvert_options: list[str]
    junctions: dict[str, str]
    entries: dict[str, str]
    exits: dict[str, str]
    vehicle_mix: dict[str, float]
    periods: list[DemandPeriod]
    exit_weights: dict[str, float]

    @property
    def duration(self) -> int:
        """Length of the demand profile in seconds."""
        return sum(p.seconds for p in self.periods)

    @property
    def junction_ids(self) -> list[str]:
        return list(self.junctions)

    def build_network(self, output: Path | None = None) -> Path:
        """Regenerate the SUMO network from the OSM extract with netconvert."""
        output = Path(output or self.net).resolve()
        cmd = [
            sumo_binary("netconvert"),
            f"--osm-files={self.osm.name}",
            *self.netconvert_options,
            "--no-warnings=true",
            f"--output-file={output}",
        ]
        # Run from the scenario folder so the file records relative paths, not this machine's.
        subprocess.run(cmd, check=True, capture_output=True, text=True, cwd=self.folder)
        # Drop the timestamp and this machine's paths so a rebuild is byte-for-byte stable.
        text = output.read_text(encoding="utf-8")
        text = re.sub(r"<!-- generated on \S+ by", "<!-- generated by", text, count=1)
        output.write_text(text.replace(str(output), output.name), encoding="utf-8")
        return output

    def write_demand(self, path: Path, seed: int, scale: float = 1.0) -> int:
        """Write a SUMO trips file for one episode; returns the number of vehicles.

        Arrivals are Poisson per entry and second, so ``seed`` changes the exact
        vehicles but not the overall pattern. ``scale`` multiplies every rate.
        """
        rng = np.random.default_rng(seed)
        types = list(self.vehicle_mix)
        type_p = np.array([self.vehicle_mix[t] for t in types], dtype=float)
        type_p /= type_p.sum()

        trips: list[tuple[int, str, str, str]] = []
        t0 = 0
        for period in self.periods:
            for entry, per_hour in period.rates.items():
                lam = scale * per_hour / 3600.0
                counts = rng.poisson(lam, size=period.seconds)
                exits = [x for x in self.exits if x != entry]
                w = np.array([self.exit_weights.get(x, 1.0) for x in exits], dtype=float)
                w /= w.sum()
                for second in np.flatnonzero(counts):
                    for _ in range(counts[second]):
                        exit_ = exits[rng.choice(len(exits), p=w)]
                        vtype = types[rng.choice(len(types), p=type_p)]
                        trips.append((t0 + int(second), entry, exit_, vtype))
            t0 += period.seconds
        trips.sort(key=lambda trip: trip[0])

        lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<routes>"]
        lines += [f"    {VEHICLE_TYPES[t]}" for t in types]
        for i, (depart, entry, exit_, vtype) in enumerate(trips):
            lines.append(
                f'    <trip id="v{i}" type="{vtype}" depart="{depart}" '
                f"from={quoteattr(self.entries[entry])} to={quoteattr(self.exits[exit_])} "
                'departLane="best" departSpeed="max"/>'
            )
        lines.append("</routes>")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return len(trips)


def available() -> list[str]:
    return sorted(p.name for p in SCENARIOS_DIR.iterdir() if (p / "scenario.yaml").is_file())


def load(name_or_path: str | Path = "kowdenahalli") -> Scenario:
    """Load a bundled scenario by name, or any folder containing a scenario.yaml."""
    folder = Path(name_or_path)
    if not (folder / "scenario.yaml").is_file():
        folder = SCENARIOS_DIR / str(name_or_path)
    spec_file = folder / "scenario.yaml"
    if not spec_file.is_file():
        raise FileNotFoundError(
            f"No scenario {name_or_path!r}. Bundled scenarios: {', '.join(available())}"
        )
    spec = yaml.safe_load(spec_file.read_text(encoding="utf-8"))

    entries = {str(k): str(v) for k, v in spec["entries"].items()}
    exits = {str(k): str(v) for k, v in spec["exits"].items()}
    periods = [
        DemandPeriod(
            seconds=int(p["minutes"] * 60), rates={str(k): float(v) for k, v in p["rates"].items()}
        )
        for p in spec["demand"]["periods"]
    ]
    for period in periods:
        unknown = set(period.rates) - set(entries)
        if unknown:
            raise ValueError(f"Demand uses unknown entries: {sorted(unknown)}")
    mix = {str(k): float(v) for k, v in spec["vehicle_mix"].items()}
    unknown_types = set(mix) - set(VEHICLE_TYPES)
    if unknown_types:
        raise ValueError(f"Unknown vehicle types: {sorted(unknown_types)}")

    return Scenario(
        name=spec["name"],
        folder=folder,
        osm=folder / spec["osm"],
        net=folder / spec["net"],
        netconvert_options=[str(o) for o in spec.get("netconvert", [])],
        junctions={str(k): str(v) for k, v in spec["junctions"].items()},
        entries=entries,
        exits=exits,
        vehicle_mix=mix,
        periods=periods,
        exit_weights={str(k): float(v) for k, v in spec["demand"].get("exit_weights", {}).items()},
    )
